config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :notes

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :book, presence: true, inclusion: { in: [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song of Solomon",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation"
  ], message: "is not a valid book" }
  validates :note_text, presence: true

  def self.valid_books
    [
      "Genesis",
      "Exodus",
      "Leviticus",
      "Numbers",
      "Deuteronomy",
      "Joshua",
      "Judges",
      "Ruth",
      "1 Samuel",
      "2 Samuel",
      "1 Kings",
      "2 Kings",
      "1 Chronicles",
      "2 Chronicles",
      "Ezra",
      "Nehemiah",
      "Esther",
      "Job",
      "Psalms",
      "Proverbs",
      "Ecclesiastes",
      "Song of Solomon",
      "Isaiah",
      "Jeremiah",
      "Lamentations",
      "Ezekiel",
      "Daniel",
      "Hosea",
      "Joel",
      "Amos",
      "Obadiah",
      "Jonah",
      "Micah",
      "Nahum",
      "Habakkuk",
      "Zephaniah",
      "Haggai",
      "Zechariah",
      "Malachi",
      "Matthew",
      "Mark",
      "Luke",
      "John",
      "Acts",
      "Romans",
      "1 Corinthians",
      "2 Corinthians",
      "Galatians",
      "Ephesians",
      "Philippians",
      "Colossians",
      "1 Thessalonians",
      "2 Thessalonians",
      "1 Timothy",
      "2 Timothy",
      "Titus",
      "Philemon",
      "Hebrews",
      "James",
      "1 Peter",
      "2 Peter",
      "1 John",
      "2 John",
      "3 John",
      "Jude",
      "Revelation"
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit
    @note = Note.find(params[:id])

    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def show
    @note = Note.find(params[:id])
  end

  def index
    @notes = Note.all
  end

  private
    def note_params
      params.require(:note).permit(:book, :chapter, :start_verse, :end_verse, :note_text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noteapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= form_with scope: :note, url: notes_path, local: true do |form| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@note.errors.count, "error") %> prohibited
        this note from being saved:
      </h2>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :book %><br>
    <%= form.text_field :book %>
  </p>

  <p>
    <%= form.label :chapter %><br>
    <%= form.number_field :chapter %>
  </p>

  <p>
    <%= form.label :start_verse %><br>
    <%= form.number_field :start_verse %>
  </p>

  <p>
    <%= form.label :end_verse %><br>
    <%= form.number_field :end_verse %>
  </p>

  <p>
    <%= form.label :note_text %><br>
    <%= form.text_area :note_text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/notes/index.html.erb
<h1>Listing Notes</h1>

<table>
  <tr>
    <th>Book</th>
    <th>Chapter</th>
    <th>Start Verse</th>
    <th>End Verse</th>
    <th>Note</th>
  </tr>

  <% @notes.each do |note| %>
    <tr>
      <td style="text-align:center"><%= note.book %></td>
      <td style="text-align:center"><%= note.chapter %></td>
      <td style="text-align:center"><%= note.start_verse %></td>
      <td style="text-align:center"><%= note.end_verse %></td>
      <td style="text-align:left"><%= note.note_text %></td>
    </tr>
  <% end %>
</table>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= form_with scope: :note, url: notes_path, local: true do |form| %>
  <p>
    <%= form.label :book %><br>
    <%= form.text_field :book %>
  </p>

  <p>
    <%= form.label :chapter %><br>
    <%= form.number_field :chapter %>
  </p>

  <p>
    <%= form.label :start_verse %><br>
    <%= form.number_field :start_verse %>
  </p>

  <p>
    <%= form.label :end_verse %><br>
    <%= form.number_field :end_verse %>
  </p>

  <p>
    <%= form.label :note_text %><br>
    <%= form.text_area :note_text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/notes/show.html.erb
<table>
  <tr>
    <th>Book</th>
    <th>Chapter</th>
    <th>Start Verse</th>
    <th>End Verse</th>
    <th>Note</th>
  </tr>
  <tr>
    <td style="text-align:center"><%= @note.book %></td>
    <td style="text-align:center"><%= @note.chapter %></td>
    <td style="text-align:center"><%= @note.start_verse %></td>
    <td style="text-align:center"><%= @note.end_verse %></td>
    <td style="text-align:left"><%= @note.note_text %></td>
  </tr>
</table>

</br>
<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/welcome/index.html.erb
<h1>NoteApp v0.1</h1>
<ul>
  <li><%= link_to 'All Notes', controller: 'notes' %></li>
  <li><%= link_to 'New Note', new_note_path %></li>
</ul>